### PR TITLE
House

### PR DESCRIPTION
**Pull request by ghost**
Initial structure of 'House' with functional components, not yet imported to App.js.

### CODE REVIEW

**Comment by Jam52** [comment]
Looks good, not sure if your intending to have the ImageContainer in the Summery component but I would keep it separate, and import it in the overall page file. That way when we come back in the future we can clearly see and easily update pthe pictures etc without having to go into the summery component, what do you think?

**Comment by ghost** [comment]
I think that's a great idea! What do you think about a json file listing
the directory roots to photos, text content etc. that would create a single
source of truth. Maybe a different format might work better though 🤔 what
do you think?

**Comment by ghost** [comment]
I agree, the image container would go nicely in the "House" component itself.

**Review by Jam52 — APPROVED** [review]
Looks good!

**Pull request merged**
